Algoritmo "exercicio_crescente"
// Disciplina   : [Linguagem e Lógica de Programação]
// Autor(a)    : Thiago Melo
// Data atual  : 21/06/2023

Var

   x, y : inteiro

Inicio

 escreval ("Digite dois numeros: ")
  leia (x)
  leia (y)
 
 enquanto x <> y faca

   se x < y entao
     escreval ("CRESCENTE")
   senao
     escreval ("DECRESCENTE")
   fimse
   
   escreval
   escreval ("Digite outros dois numeros: ")
    leia (x)
    leia (y)
   
 fimenquanto
 


Fimalgoritmo