Algoritmo "sequencia_impares"
// Disciplina   : [Linguagem e Lógica de Programação]
// Autor(a)    : Thiago Melo
// Data atual  : 20/08/2023
Var
// Seção de Declarações das variáveis 

 x, i : inteiro



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

  escreval ("Digite o valor de X: ")
  leia (x)
  
  para i de 1 ate x faca
     se i % 2 <> 0 entao
     escreval
     escreval (i)
     fimse
  fimpara

Fimalgoritmo