Algoritmo "exercicio_soma"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Execução do exercício "soma"
// Autor(a)    : Thiago Melo
// Data atual  : 27/04/2023
Var

  x, y : inteiro
  soma : inteiro

Inicio

  escreval ("Responda conforme solicitado")
  escreval
  escreva ("Digite o valor de X: ")
  leia (x)
  escreva ("Digite o valor de Y: ")
  leia (y)
  escreval
  
  soma <- x + y
  
  escreval ("Soma dos valores: " , soma)
  
Fimalgoritmo