Algoritmo "senha_fixa"
// Disciplina   : [Linguagem e Lógica de Programação]
// Autor(a)    : Thiago Melo
// Data atual  : 22/06/2023
Var

  senha : inteiro


Inicio

  escreva ("Digite a senha: ")
  leia (senha)
  
  enquanto senha <> 1993 faca
    escreval ("Senha Invalida! Tente novamente: ")
    leia (senha)
  fimenquanto
  
  se senha = 1993 entao
    escreval ("Acesso permitido!")
  fimse


Fimalgoritmo