Algoritmo "teste_enquanto"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Teste da estrutura repetitiva "enquanto"
// Autor(a)    : Thiago Melo
// Data atual  : 20/06/2023
Var

  x, soma : inteiro

Inicio

  escreva ("Digite o primeiro numero: ")
  leia (x)
  
  soma <- 0
  
  enquanto x <> 0 faca
    soma <- soma + x
    escreva ("Digite outro número: ")
    leia (x)
  fimenquanto
  
  escreval
  escreval ("Soma: " , soma)


Fimalgoritmo